export { default as Employees } from './Employees';
export { default as Editor } from './Editor';
export { default as Customers } from './Customers';
export { default as ColorPicker } from './ColorPicker';
export { default as Products } from './Products';
export { default as Order } from './Order';
export { default as OrderManager } from './OrderManager';
export { default as ProductDetail } from './ProductDetail';
export { default as Home } from './Home';